In [1]:
import requests
from bs4 import BeautifulSoup
from urllib.request import urlopen
import pandas as pd
from html.parser import HTMLParser
import re

In [2]:
names = {'Iron-Man',
        'Incredible-Hulk-The',
        'Thor',
        'Iron-Man-2',
        'Captain-America-The-First-Avenger',
        'Avengers-The-(2012)',
        'Iron-Man-3',
        'Thor-The-Dark-World',
        'Captain-America-The-Winter-Soldier',
        'Guardians-of-the-Galaxy',
        'Avengers-Age-of-Ultron',
        'Ant-Man',
        'Captain-America-Civil-War',
        'Doctor-Strange-(2016)',
        'Guardians-of-the-Galaxy-Vol-2',
        'Spider-Man-Homecoming',
        'Thor-Ragnarok',
        'Black-Panther',
        'Avengers-Infinity-War',
        'Ant-Man-and-the-Wasp',
        'Captain-Marvel-(2019)',
        'Avengers-Endgame-(2019)'
         }

In [4]:
track=0
for name in names:
    track+=1
    print(name)
    data = requests.get('https://www.the-numbers.com/movie/' + name + '#tab=box-office')
    soup = BeautifulSoup(data.text, 'html.parser')
    div = soup.find('div' , {'id': 'box_office_chart'})
    table = div.find('table')
    tbody = table.find('tbody')
    html = table.encode(encoding='ISO-8859-1')
    dfs = pd.read_html(html,header=0)
    df = dfs[0]
    df['movie'] = name
    if track==1:
        all_df = df
    elif track>=2:
        all_df = pd.concat([all_df, df])
#    df.to_csv('movie'+str(name)+'.csv', encoding='ISO-8859-1')
    print(name)
all_df.to_csv('marvel_universe.csv', encoding='ISO-8859-1')
df

Thor
Thor
Doctor-Strange-(2016)
Doctor-Strange-(2016)
Ant-Man-and-the-Wasp
Ant-Man-and-the-Wasp
Avengers-Infinity-War
Avengers-Infinity-War
Iron-Man-3
Iron-Man-3
Thor-Ragnarok
Thor-Ragnarok
Avengers-Age-of-Ultron
Avengers-Age-of-Ultron
Incredible-Hulk-The
Incredible-Hulk-The
Black-Panther
Black-Panther
Captain-America-The-Winter-Soldier
Captain-America-The-Winter-Soldier
Avengers-Endgame-(2019)
Avengers-Endgame-(2019)
Iron-Man-2
Iron-Man-2
Thor-The-Dark-World
Thor-The-Dark-World
Iron-Man
Iron-Man
Captain-Marvel-(2019)
Captain-Marvel-(2019)
Spider-Man-Homecoming
Spider-Man-Homecoming
Avengers-The-(2012)
Avengers-The-(2012)
Captain-America-The-First-Avenger
Captain-America-The-First-Avenger
Ant-Man
Ant-Man
Guardians-of-the-Galaxy
Guardians-of-the-Galaxy
Captain-America-Civil-War
Captain-America-Civil-War
Guardians-of-the-Galaxy-Vol-2
Guardians-of-the-Galaxy-Vol-2

,Date,Rank,Gross,% Change,Theaters,Per Theater,Total Gross,Week,movie
0,"May 5, 2017",1,"$146,510,104",NaN,4347,"$33,704","$146,510,104",1,Guardians-of-the-Galaxy-Vol-2
1,"May 12, 2017",1,"$65,263,492",-55%,4347,"$15,013","$248,420,911",2,Guardians-of-the-Galaxy-Vol-2
2,"May 19, 2017",2,"$34,653,754",-47%,4347,"$7,972","$301,391,228",3,Guardians-of-the-Galaxy-Vol-2
3,"May 26, 2017",2,"$20,907,121",-40%,3871,"$5,401","$334,223,048",4,Guardians-of-the-Galaxy-Vol-2
4,"Jun 2, 2017",4,"$9,839,370",-53%,3507,"$2,806","$355,580,702",5,Guardians-of-the-Galaxy-Vol-2
5,"Jun 9, 2017",5,"$6,312,367",-36%,2911,"$2,168","$366,431,539",6,Guardians-of-the-Galaxy-Vol-2
6,"Jun 16, 2017",9,"$5,071,732",-20%,1813,"$2,797","$374,942,747",7,Guardians-of-the-Galaxy-Vol-2
7,"Jun 23, 2017",10,"$3,023,042",-40%,1468,"$2,059","$380,236,369",8,Guardians-of-the-Galaxy-Vol-2
8,"Jun 30, 2017",13,"$1,539,519",-49%,966,"$1,594","$383,383,494",9,Guardians-of-the-Galaxy-Vol-2
9,"Jul 7, 2017",13,"$860,020",-44%,660,"$1,303","$385,560,026",10,Guardians-of-the-Galaxy-Vol-2
10,"Jul 14, 2017",13,"$509,535",-41%,399,"$1,277","$386,571,925",11,Guardians-of-the-Galaxy-Vol-2
11,"Jul 21, 2017",17,"$364,450",-28%,268,"$1,360","$387,259,952",12,Guardians-of-the-Galaxy-Vol-2
12,"Jul 28, 2017",20,"$277,201",-24%,231,"$1,200","$387,764,608",13,Guardians-of-the-Galaxy-Vol-2
13,"Aug 4, 2017",19,"$453,768",+64%,252,"$1,801","$388,399,203",14,Guardians-of-the-Galaxy-Vol-2
14,"Aug 11, 2017",26,"$257,117",-43%,210,"$1,224","$388,879,065",15,Guardians-of-the-Galaxy-Vol-2
15,"Aug 18, 2017",28,"$187,598",-27%,195,$962,"$389,194,993",16,Guardians-of-the-Galaxy-Vol-2
16,"Aug 25, 2017",35,"$118,152",-37%,299,$395,"$389,386,420",17,Guardians-of-the-Galaxy-Vol-2
17,"Sep 1, 2017",34,"$217,105",+84%,196,"$1,108","$389,646,310",18,Guardians-of-the-Galaxy-Vol-2
18,"Sep 8, 2017",42,"$53,202",-75%,129,$412,"$389,760,116",19,Guardians-of-the-Galaxy-Vol-2
19,"Sep 15, 2017",48,"$26,353",-50%,80,$329,"$389,804,217",20,Guardians-of-the-Galaxy-Vol-2

In [ ]:
all_df